swagger: '2.0'
info:
  version: '1.0.0'
  title: Store Mission API
  description: API for managing store missions
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /store/mission/complete:
    post:
      tags:
        - Store Mission
      summary: Complete a mission
      description: Marks a mission as completed.
      parameters:
        - in: body
          name: body
          description: ID of the mission to complete
          required: true
          schema:
            type: object
            properties:
              mission_id:
                type: integer
                example: 1
      responses:
        200:
          description: Mission completed successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "Mission completed successfully"
        400:
          description: Bad request
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: 4001
              message:
                type: string
                example: "Invalid mission ID"
        500:
          description: Server error
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: 5000
              message:
                type: string
                example: "Failed to complete mission"
