swagger: '2.0'
info:
  version: '1.0.0'
  title: Store Mission API
  description: API for fetching store missions
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /missions:
    get:
      tags:
        - Store Mission
      summary: Fetch all missions for a store
      description: Retrieves all missions for the specified store.
      parameters:
        - name: store_id
          in: query
          description: ID of the store
          required: true
          type: integer
          example: 1
      responses:
        200:
          description: List of missions
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "Mission list fetched successfully"
              data:
                type: array
                items:
                  type: object
                  properties:
                    mission_id:
                      type: integer
                      example: 1
                    store_id:
                      type: integer
                      example: 1
                    user_id:
                      type: integer
                      example: 1
                    mission_text:
                      type: string
                      example: "Complete the setup"
                    mission_status:
                      type: string
                      enum:
                        - Pending
                        - Completed
                      example: "Pending"
        404:
          description: No missions found
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: 4004
              message:
                type: string
                example: "No missions found"
        500:
          description: Server error
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: 5000
              message:
                type: string
                example: "Failed to fetch missions"
